// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	azservicebus "github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus"
	mock "github.com/stretchr/testify/mock"
)

// OutMessageOption is an autogenerated mock type for the OutMessageOption type
type OutMessageOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *OutMessageOption) Execute(_a0 *azservicebus.Message) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewOutMessageOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewOutMessageOption creates a new instance of OutMessageOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOutMessageOption(t mockConstructorTestingTNewOutMessageOption) *OutMessageOption {
	mock := &OutMessageOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
