// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	azbus "github.com/datatrails/go-datatrails-common/azbus"
	mock "github.com/stretchr/testify/mock"
)

// ReceiverOption is an autogenerated mock type for the ReceiverOption type
type ReceiverOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ReceiverOption) Execute(_a0 *azbus.Receiver) {
	_m.Called(_a0)
}

// NewReceiverOption creates a new instance of ReceiverOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceiverOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReceiverOption {
	mock := &ReceiverOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
